version: "3.8"

services:
  customer:
    image: microservices_study/customer-service:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - microservices-study-network

  accounts:
    image: microservices_study/accounts-service:latest
    mem_limit: 700m
    ports:
      - "8081:8081"
    networks:
      - microservices-study-network

  cards:
    image: microservices_study/cards-service:latest
    mem_limit: 700m
    ports:
      - "8082:8082"
    networks:
      - microservices-study-network

  loans:
    image: microservices_study/loans-service:latest
    mem_limit: 700m
    ports:
      - "8083:8083"
    networks:
      - microservices-study-network

networks:
  microservices-study-network: