server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:file:C:/Users/Sobhen/Desktop/My_Space/Study_Drive/Miscroservices/Spring_Boot_Cloud/Udemy_MS_Spring_Docker_K8/workspace/data/loansDB
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

customer:
  service:
    base-url: http://localhost:8080