DROP TABLE IF EXISTS T_CUSTOMER;

CREATE TABLE `T_CUSTOMER` (
  `CUSTOMER_ID` int AUTO_INCREMENT  PRIMARY KEY,
  `CUSTOMER_NAME` varchar(100) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `MOBILE_NUMBER` varchar(20) NOT NULL,
  `CREATE_DT` date DEFAULT NULL
);

INSERT INTO `T_CUSTOMER` (`CUSTOMER_NAME`,`EMAIL`,`MOBILE_NUMBER`,`CREATE_DT`)
 VALUES ('Sobhen Mishra','sobhen@gmail.com','9876548337',CURDATE());

 INSERT INTO `T_CUSTOMER` (`CUSTOMER_NAME`,`EMAIL`,`MOBILE_NUMBER`,`CREATE_DT`)
  VALUES ('Siddhiksha','Siddhiksha@gmail.com','9642200074',CURDATE());