DROP TABLE IF EXISTS T_CARDS;

CREATE TABLE `T_CARDS` (
  `CARD_ID` int NOT NULL AUTO_INCREMENT,
  `CARD_NUMBER` varchar(100) NOT NULL,
  `CUSTOMER_ID` int NOT NULL,
  `CARD_TYPE` varchar(100) NOT NULL,
  `TOTAL_LIMIT` int NOT NULL,
  `AMOUNT_USED` int NOT NULL,
  `AVAILABLE_AMOUNT` int NOT NULL,
  `CREATE_DT` date DEFAULT NULL,
  PRIMARY KEY (`CARD_ID`)
);


INSERT INTO `T_CARDS` (`CARD_NUMBER`, `CUSTOMER_ID`, `CARD_TYPE`, `TOTAL_LIMIT`, `AMOUNT_USED`, `AVAILABLE_AMOUNT`, `CREATE_DT`)
 VALUES ('4565XXXX4656', 1, 'Credit', 10000, 500, 9500, CURDATE());

