DROP TABLE IF EXISTS T_ACCOUNTS;

CREATE TABLE `T_ACCOUNTS` (
  `ACCOUNT_ID` int AUTO_INCREMENT  PRIMARY KEY,
  `CUSTOMER_ID` int NOT NULL,
  `ACCOUNT_NUMBER` int NOT NULL,
  `ACCOUNT_TYPE` varchar(100) NOT NULL,
  `BRANCH_ADDRESS` varchar(200) NOT NULL,
  `CREATE_DT` date DEFAULT NULL
);


INSERT INTO `T_ACCOUNTS` (`CUSTOMER_ID`, `ACCOUNT_NUMBER`, `ACCOUNT_TYPE`, `BRANCH_ADDRESS`, `create_dt`)
 VALUES (1, 186576453, 'Savings', '123 Main Street, New York', CURDATE());